import { Header } from "@/shared/ui";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import CssBaseline from "@mui/material/CssBaseline";

export const metadata: Metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <CssBaseline />
      <body className={`${GeistSans.className} antialiased`}>
        <Header />
        <main className="container">{children}</main>
      </body>
    </html>
  );
}
