import { Header } from "@/shared/ui";
import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import CssBaseline from "@mui/material/CssBaseline";
import { Provider } from "./providers";

export const metadata: Metadata = {
  title: "Rick and Morty",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${GeistSans.className} antialiased bg-black text-white`}
      >
        <CssBaseline />

        <Provider>
          <Header />
          <main
            className="container mx-auto"
            style={{
              paddingLeft: "1rem",
              paddingRight: "1rem",
              paddingTop: "2rem",
              paddingBottom: "2rem",
            }}
          >
            {children}
          </main>
        </Provider>
      </body>
    </html>
  );
}
